export const expandedCurated: Record<string, string> = {
  "about": "On the subject of; concerning",
  "above": "At a higher level or layer than",
  "across": "From one side to the other of something",
  "after": "In the time following an event or another period of time",
  "again": "Another time; once more",
  "against": "In opposition to",
  "abandon": "To leave someone or something that you are responsible for",
  "ability": "Possession of the means or skill to do something",
  "able": "Having the power, skill, means, or opportunity to do something",
  "absolute": "Not qualified or diminished in any way; total",
  "accept": "Consent to receive or undertake something offered",
  "access": "The means or opportunity to approach or enter a place",
  "accident": "An unfortunate incident that happens unexpectedly and unintentionally",
  "account": "A report or description of an event or experience",
  "accurate": "Correct in all details; exact",
  "achieve": "Reach or attain by effort, skill, or courage",
  "acid": "A chemical substance that neutralizes alkalis",
  "acknowledge": "Accept or admit the existence or truth of",
  "acquire": "Buy or obtain for oneself",
  "act": "Take action; do something",
  "action": "The fact or process of doing something",
  "active": "Engaging or ready to engage in physically energetic pursuits",
  "activity": "A thing that a person or group does or has done",
  "actor": "A person whose profession is acting on the stage, in movies, or on television",
  "actual": "Existing in fact or reality; real",
  "adapt": "Make something suitable for a new use or purpose",
  "add": "Join something to something else so as to increase the size, number, or amount",
  "addition": "The action or process of adding something to something else",
  "additional": "Added, extra, or supplementary",
  "address": "The particulars of the place where someone lives or an organization is situated",
  "adequate": "Satisfactory or acceptable in quality or quantity",
  "adjust": "Alter or move something slightly in order to achieve the desired fit, appearance, or result",
  "administration": "The process or activity of running a business, organization, etc.",
  "admire": "Regard with respect or warm approval",
  "admit": "Confess to be true or to be the case",
  "adopt": "Legally take another's child and bring it up as one's own",
  "adult": "A person who is fully grown or developed",
  "advance": "Move forward in a purposeful way",
  "advantage": "A condition or circumstance that puts one in a favorable or superior position",
  "adventure": "An unusual and exciting, typically hazardous, experience or activity",
  "advice": "Guidance or recommendations offered with regard to prudent future action",
  "advise": "Offer suggestions about the best course of action to someone",
  "affair": "An event or sequence of events of a specified kind or that has previously been referred to",
  "affect": "Have an effect on; make a difference to",
  "afford": "Have enough money to pay for",
  "afraid": "Feeling fear or anxiety; frightened",
  "age": "The length of time that a person or thing has existed",
  "agency": "A business or organization established to provide a particular service",
  "agent": "A person who acts on behalf of another person or group",
  "ago": "Before the present; earlier",
  "agree": "Have the same opinion about something; concur",
  "agreement": "Harmony or accordance in opinion or feeling",
  "ahead": "Further forward in space or time",
  "aid": "Help, typically of a practical nature",
  "aim": "Point or direct a weapon or camera at a target",
  "air": "The invisible gaseous substance surrounding the earth",
  "alarm": "An anxious awareness of danger",
  "alcohol": "A colorless volatile flammable liquid which is the intoxicating constituent of wine, beer, spirits, and other drinks",
  "alive": "Living, not dead",
  "all": "Used to refer to the whole quantity or amount of something",
  "allow": "Give (someone) permission to do something",
  "almost": "Not quite; very nearly",
  "alone": "Having no one else present",
  "along": "Moving in a constant direction on a path or any more or less horizontal surface",
  "already": "Before or by now or the time in question",
  "also": "In addition; too",
  "alter": "Change or cause to change in character or composition, typically in a comparatively small but significant way",
  "alternative": "One of two or more available possibilities",
  "although": "In spite of the fact that; even though",
  "always": "At all times; on all occasions",
  "amaze": "Surprise (someone) greatly; astonish",
  "ambition": "A strong desire to do or to achieve something, typically requiring determination and hard work",
  "among": "Situated more or less centrally in relation to several other things",
  "amount": "A quantity of something, especially the total of a thing or things in number, size, value, or extent",
  "ancient": "Belonging to the very distant past and no longer in existence",
  "and": "Used to connect words of the same part of speech, clauses, or sentences",
  "anger": "A strong feeling of annoyance, displeasure, or hostility",
  "angle": "The space between two intersecting lines or surfaces at or close to the point where they meet",
  "angry": "Feeling or showing strong annoyance, displeasure, or hostility",
  "animal": "A living organism that feeds on organic matter",
  "announce": "Make a formal public statement about a fact, occurrence, or intention",
  "annual": "Occurring once every year",
  "another": "Used to refer to an additional person or thing of the same type",
  "answer": "A thing said, written, or done to deal with or as a reaction to a question, statement, or situation",
  "any": "Used to refer to one or some of a thing or number of things, no matter how much or many",
  "anybody": "Anyone",
  "anyhow": "Anyway",
  "anyone": "Any person or people",
  "anything": "Used to refer to a thing, no matter what",
  "anyway": "Used to confirm or support a prior point or claim",
  "anywhere": "In or to any place",
  "apart": "To or at a distance from each other in space or time",
  "apartment": "A suite of rooms forming one residence",
  "apparent": "Clearly visible or understood; obvious",
  "appeal": "Make a serious or urgent request, typically to the public",
  "appear": "Come into sight; become visible or noticeable",
  "appearance": "The way that someone or something looks",
  "apply": "Make a formal application or request",
  "appoint": "Assign a job or role to (someone)",
  "approve": "Believe that someone or something is good or acceptable",
  "area": "A region or part of a town, a country, or the world",
  "argue": "Give reasons or cite evidence in support of an idea, action, or theory, typically with the aim of persuading others to share one's view",
  "argument": "An exchange of diverging or opposite views, typically a heated or angry one",
  "arm": "Each of the two upper limbs of the human body from the shoulder to the hand",
  "army": "An organized military force equipped for fighting on land",
  "around": "On every side of",
  "arrange": "Put things in a neat, attractive, or required order",
  "arrest": "Seize (someone) by legal authority and take into custody",
  "arrival": "The action or process of arriving",
  "arrive": "Reach a destination at the end of a journey or a stage in a journey",
  "article": "A particular item or object",
  "artificial": "Made or produced by human beings rather than occurring naturally",
  "artist": "A person who creates paintings or drawings as a profession or hobby",
  "as": "Used in comparisons to refer to the extent or degree of something",
  "ashamed": "Embarrassed or guilty because of one's actions, characteristics, or associations",
  "aside": "To one side; out of the way",
  "ask": "Say something in order to obtain information or advice",
  "asleep": "In a state of sleep",
  "aspect": "A particular part or feature of something",
  "assist": "Help (someone), typically by doing a share of the work",
  "associate": "Connect (someone or something) with something else in one's mind",
  "assume": "Suppose to be the case, without proof",
  "assure": "Tell someone something positively or confidently to dispel any doubts they may have",
  "at": "Expressing location or arrival in a particular place or position",
  "atmosphere": "The envelope of gases surrounding the earth or another planet",
  "attach": "Join or fasten (something) to something else",
  "attack": "An aggressive and violent action against a person or place",
  "attempt": "An effort to achieve or complete a difficult task or action",
  "attend": "Be present at (an event, meeting, or function)",
  "attention": "Notice taken of someone or something; the regarding of someone or something as interesting or important",
  "attitude": "A settled way of thinking or feeling about someone or something, typically one that is reflected in a person's behavior",
  "attract": "Cause (someone) to have a liking for or interest in something",
  "audience": "The assembled spectators or listeners at a public event, such as a play, movie, concert, or meeting",
  "aunt": "The sister of one's father or mother or the wife of one's uncle",
  "author": "A writer of a book, article, or report",
  "authority": "The power or right to give orders, make decisions, and enforce obedience",
  "available": "Able to be used or obtained; at someone's disposal",
  "average": "A number expressing the central or typical value in a set of data",
  "avoid": "Keep away from or stop oneself from doing (something)",
  "awake": "Not asleep",
  "award": "A prize or other mark of recognition given in honor of an achievement",
  "aware": "Having knowledge or perception of a situation or fact",
  "away": "To or at a distance from a particular place, person, or thing",
  "awful": "Very bad or unpleasant",
  "baby": "A very young child or animal",
  "back": "The rear surface of the human body from the shoulders to the hips",
  "background": "The area or scenery behind the main object of contemplation, especially when perceived as a framework for it",
  "balance": "An even distribution of weight enabling someone or something to remain upright and steady",
  "ball": "A solid or hollow spherical or egg-shaped object that is kicked, thrown, or hit in a game",
  "band": "A flat, thin strip or loop of material used as a fastener, for reinforcement, or as decoration",
  "bank": "A financial establishment that invests money deposited by customers, pays it out when required, makes loans at interest, and exchanges currency",
  "bar": "A long rigid piece of metal or wood, used as a barrier, fastener, or lever",
  "base": "The lowest part or edge of something, especially the part on which it rests or is supported",
  "basic": "Forming an essential foundation or starting point; fundamental",
  "basis": "The underlying support or foundation for an idea, argument, or process",
  "basket": "A container used for holding or carrying things, typically made from interwoven strips of cane or wire",
  "bath": "An act or process of immersing and washing one's body in a large container of water",
  "battle": "A sustained fight between large organized armed forces",
  "be": "Exist",
  "beach": "A pebbly or sandy shore, especially by the ocean between high- and low-water marks",
  "beam": "A long, sturdy piece of squared timber or metal spanning an opening or part of a building",
  "bear": "A large, heavy, mammal that walks on the soles of its feet, having thick fur and a very short tail",
  "beard": "A growth of hair on the chin and lower cheeks of a man's face",
  "beat": "Strike (a person or an animal) repeatedly and violently so as to hurt or injure them, typically with an implement such as a club or whip",
  "beautiful": "Pleasing the senses or mind aesthetically",
  "beauty": "A combination of qualities, such as shape, color, or form, that pleases the aesthetic senses, especially the sight",
  "because": "For the reason that; since",
  "become": "Begin to be",
  "bed": "A piece of furniture for sleep or rest, typically a framework with a mattress and coverings",
  "beer": "An alcoholic drink made from yeast-fermented malt flavored with hops",
  "before": "During the period of time preceding a particular event, date, or time",
  "beg": "Ask someone earnestly or humbly for something",
  "begin": "Start; perform or undergo the first part of (an action or activity)",
  "beginning": "The point in time or space at which something starts",
  "behave": "Act or conduct oneself in a specified way, especially toward others",
  "behavior": "The way in which one acts or conducts oneself, especially toward others",
  "behind": "At or to the far side of (something), typically so as to be hidden by it",
  "being": "Existence",
  "belief": "An acceptance that a statement is true or that something exists",
  "believe": "Accept (something) as true; feel sure of the truth of",
  "bell": "A hollow metal object, typically in the shape of a deep inverted cup widening at the lip, that sounds a clear musical note when struck, typically by a means of a clapper inside",
  "belong": "Be the property of",
  "below": "At a lower level or layer than",
  "belt": "A strip of leather or other material worn around the waist or across the chest to support clothes or carry weapons",
  "bench": "A long seat for several people, typically made of wood or stone",
  "bend": "Shape or force (something straight) into a curve or angle",
  "benefit": "An advantage or profit gained from something",
  "beside": "At the side of; next to",
  "best": "Of the most excellent, effective, or desirable type or quality",
  "bet": "Risk a sum of money or valued item against someone else's on the basis of the outcome of an unpredictable event",
  "better": "More excellent, effective, or desirable",
  "between": "At, into, or across the space separating (two objects or regions)",
  "beyond": "At or to the further side of",
  "bicycle": "A vehicle consisting of two wheels held in a frame one behind the other, propelled by pedals and steered with handlebars attached to the front wheel",
  "bid": "Offer (a certain price) for something, especially at an auction",
  "big": "Of considerable size, extent, or intensity",
  "bill": "An amount of money owed for goods supplied or services rendered, set out in a printed or written statement of charges",
  "bin": "A receptacle in which to deposit trash",
  "bird": "A warm-blooded egg-laying vertebrate distinguished by the possession of feathers, wings, and a beak and (typically) by being able to fly",
  "birth": "The emergence of a baby or other young from the body of its mother; the start of life as a physically separate being",
  "birthday": "The anniversary of the day on which a person was born, typically treated as an occasion for celebration and the giving of gifts",
  "bit": "A small piece, part, or quantity of something",
  "bite": "Use the teeth to cut into or through something",
  "bitter": "Having a sharp, pungent taste or smell; not sweet",
  "black": "Of the very darkest color owing to the absence of or complete absorption of light; the opposite of white",
  "blade": "The flat cutting edge of a knife, saw, or other tool or weapon",
  "blame": "Assign responsibility for a fault or wrong",
  "blank": "Bare; empty; containing no information or mark",
  "blind": "Unable to see",
  "block": "A large solid piece of hard material, especially rock, stone, or wood, typically with flat surfaces on each side",
  "blood": "The red liquid that circulates in the arteries and veins of humans and other vertebrate animals, carrying oxygen to and carbon dioxide from the tissues of the body",
  "blow": "Expel air through pursed lips",
  "blue": "Of a color intermediate between green and violet, as of the sky or sea on a sunny day",
  "board": "A long, thin, flat piece of wood or other hard material, used for floors or other building purposes",
  "boat": "A small vessel for traveling over water, propelled by oars, sails, or an engine",
  "body": "The physical structure of a person or an animal, including the bones, flesh, and organs",
  "boil": "With reference to a liquid reach or cause to reach the temperature at which it bubbles and turns into vapor",
  "bomb": "A container filled with explosive, incendiary, or other material, designed to explode on impact or when detonated by a time mechanism, remote-control device, or lit fuse",
  "bone": "Any of the pieces of hard, whitish tissue making up the skeleton in humans and other vertebrates",
  "book": "A written or printed work consisting of pages glued or sewn together along one side and bound in covers",
  "boot": "A sturdy item of footwear covering the foot, the ankle, and sometimes the lower leg",
  "border": "A line separating two political or geographical areas, especially countries",
  "bore": "Make (a hole) in something, especially with a revolving tool",
  "born": "Existing as a result of birth",
  "borrow": "Take and use (something that belongs to someone else) with the intention of returning it",
  "boss": "A person who is in charge of a worker or organization",
  "both": "Used for emphasis to refer to two people or things, regarded and identified together",
  "bother": "Take the trouble to do something",
  "bottle": "A glass or plastic container with a narrow neck, used for storing drinks or other liquids",
  "bottom": "The lowest point or part of something",
  "bound": "Walk or run with leaping strides",
  "bowl": "A round, deep dish or basin used for food or liquid",
  "box": "A container with a flat base and sides, typically square or rectangular and having a lid",
  "boy": "A male child or young man",
  "brain": "An organ of soft nervous tissue contained in the skull of vertebrates, functioning as the coordinating center of sensation and intellectual and nervous activity",
  "branch": "A part of a tree which grows out from the trunk or from a bough",
  "brass": "A yellow alloy of copper and zinc",
  "brave": "Ready to face and endure danger or pain; showing courage",
  "bread": "Food made of flour, water, and yeast or another leavening agent, mixed together and baked",
  "break": "Separate or cause to separate into pieces as a result of a blow, shock, or strain",
  "breakfast": "A meal eaten in the morning, the first of the day",
  "breast": "Either of the two soft protruding organs on the upper front of a woman's body that secrete milk after childbirth",
  "breath": "The air taken into or expelled from the lungs",
  "breathe": "Take air into the lungs and then expel it, especially as a regular physiological process",
  "breeze": "A gentle wind",
  "bridge": "A structure carrying a road, path, railroad, or canal across a river, ravine, road, railroad, or other obstacle",
  "brief": "Of short duration",
  "bright": "Giving out or reflecting a lot of light; shining",
  "bring": "Take or go with (someone or something) to a place",
  "broad": "Having an ample distance from side to side; wide",
  "brother": "A man or boy in relation to other sons and daughters of his parents",
  "brown": "Of a color produced by mixing red, yellow, and black, as of dark wood or rich soil",
  "brush": "An implement with a handle and a block of bristles, hair, or wire, used for cleaning, polishing, or painting",
  "build": "Construct (something) by putting parts or material together",
  "building": "A structure with a roof and walls, such as a house, school, or factory",
  "burn": "Of a fire be hot and bright",
  "burst": "Break open or apart suddenly and violently, especially as a result of an internal pressure",
  "bury": "Put or hide under ground",
  "bus": "A large motor vehicle carrying passengers by road, typically one serving the public on a fixed route and for a fare",
  "business": "A person's regular occupation, profession, or trade",
  "busy": "Having a great deal to do",
  "but": "Used to introduce a phrase or clause contrasting with what has already been mentioned",
  "butter": "A pale yellow edible fatty substance made by churning cream and used as a spread or in cooking",
  "button": "A small disk or knob sewn onto a garment, either to fasten it by being pushed through a slit called a buttonhole, or for decoration",
  "buy": "Obtain in exchange for payment",
  "by": "Identifying the agent performing an action",
  "cabinet": "A cupboard with shelves or drawers for storing or displaying articles",
  "cage": "A structure of bars or wires in which birds or other animals are confined",
  "cake": "An item of soft, sweet food made from a mixture of flour, shortening, eggs, sugar, and other ingredients, baked and often decorated",
  "calculate": "Determine (the amount or number of something) mathematically",
  "call": "Cry out to (someone) in order to summon them or attract their attention",
  "calm": "Not showing or feeling nervousness, anger, or other strong emotions",
  "camera": "A device for recording visual images in the form of photographs, film, or video signals",
  "camp": "A place with temporary accommodation of huts, tents, or other structures, typically used by soldiers, refugees, prisoners, or travelers",
  "can": "Be able to",
  "cancel": "Decide or announce that (a planned event) will not take place",
  "cancer": "A disease caused by an uncontrolled division of abnormal cells in a part of the body",
  "candidate": "A person who applies for a job or is nominated for election",
  "candy": "A sweet food made with sugar or syrup combined with fruit, chocolate, or nuts",
  "cap": "A kind of soft, flat hat without a brim, and sometimes having a visor",
  "capable": "Having the power or ability needed to do something",
  "capacity": "The maximum amount that something can contain",
  "capital": "The most important city or town of a country or region, usually its seat of government and administrative center",
  "captain": "The person in command of a ship",
  "capture": "Take into one's possession or control by force",
  "car": "A road vehicle, typically with four wheels, powered by an internal combustion engine and able to carry a small number of people",
  "card": "A piece of thick, stiff paper or thin pasteboard, in particular one used for writing or printing on",
  "care": "The provision of what is necessary for the health, welfare, maintenance, and protection of someone or something",
  "career": "An occupation undertaken for a significant period of a person's life and with opportunities for progress",
  "careful": "Making sure of avoiding potential danger, mishap, or harm; cautious",
  "careless": "Not giving sufficient attention or thought to avoiding harm or errors",
  "carpet": "A floor covering made from thick woven fabric",
  "carry": "Support and move (someone or something) from one place to another",
  "case": "An instance of a particular situation; an example of something occurring",
  "cash": "Money in coins or notes, as distinct from checks, money orders, or credit",
  "cast": "Throw (something) forcefully in a specified direction",
  "cat": "A small domesticated carnivorous mammal with soft fur, a short snout, and retractile claws",
  "catch": "Intercept and hold (something which has been thrown, propelled, or dropped)",
  "cause": "A person or thing that gives rise to an action, phenomenon, or condition",
  "cave": "A natural underground chamber in a hillside or cliff",
  "ceiling": "The upper interior surface of a room or other similar compartment",
  "celebrate": "Acknowledge (a significant or happy day or event) with a social gathering or enjoyable activity",
  "cell": "A small room in which a prisoner is locked or in which a monk or nun sleeps",
  "center": "The middle point of a circle or sphere, equidistant from every point on the circumference or surface",
  "central": "Of, at, or forming the center",
  "century": "A period of one hundred years",
  "certain": "Able to be firmly relied on to happen or be the case",
  "certainly": "Used to emphasize the speaker's belief in what is being said",
  "chain": "A series of interconnected typical metal links",
  "chair": "A separate seat for one person, typically with a back and four legs",
  "chairman": "A person, especially a man, designated to preside over a meeting",
  "challenge": "A call to take part in a contest or competition, especially a duel",
  "chamber": "A large room used for formal or public events",
  "chance": "A possibility of something happening",
  "change": "Make or become different",
  "channel": "A length of water wider than a strait, joining two larger areas of water, especially two seas",
  "chapter": "A main division of a book, typically with a number or title",
  "character": "The mental and moral qualities distinctive to an individual",
  "charge": "Demand (an amount) as a price from someone for a service rendered or goods supplied",
  "charity": "An organization set up to provide help and raise money for those in need",
  "chart": "A sheet of information in the form of a table, graph, or diagram",
  "chase": "Pursue in order to catch or catch up with",
  "cheap": "Low in price; worth more than its cost",
  "check": "Examine (something) in order to determine its accuracy, quality, or condition, or to detect the presence of something",
  "cheek": "Either side of the face below the eye",
  "cheese": "A food made from the pressed curds of milk",
  "chemical": "Relating to chemistry, or the interactions of substances as studied in chemistry",
  "chest": "The front surface of a person's or animal's body between the neck and the abdomen",
  "chicken": "A domestic fowl kept for its eggs or meat, especially a young one",
  "chief": "A leader or ruler of a people or clan",
  "child": "A young human being below the age of puberty or below the legal age of majority",
  "childhood": "The state of being a child",
  "chip": "A small piece of something (especially food) cut or broken off a larger piece",
  "choice": "An act of selecting or making a decision when faced with two or more possibilities",
  "choose": "Pick out or select (someone or something) as being the best or most appropriate of two or more alternatives",
  "church": "A building used for public Christian worship",
  "cigarette": "A slender cylinder of finely cut tobacco rolled in paper for smoking",
  "circle": "A round plane figure whose boundary (the circumference) consists of points equidistant from a fixed point (the center)",
  "circumstance": "A fact or condition connected with or relevant to an event or action",
  "citizen": "A legally recognized subject or national of a state or commonwealth, either native or naturalized",
  "city": "A large town",
  "civil": "Of or relating to ordinary citizens and their concerns, as distinct from military or ecclesiastical matters",
  "claim": "State or assert that something is the case, typically without providing evidence or proof",
  "class": "A set or category of things having some property or attribute in common and differentiated from others by kind, type, or quality",
  "classic": "Judged over a period of time to be of the highest quality and outstanding of its kind",
  "classroom": "A room in which a class of pupils or students is taught",
  "clean": "Free from dirt, marks, or stains",
  "clear": "Easy to perceive, understand, or interpret",
  "clearly": "In a way that is easy to see, hear, read, or understand",
  "clerk": "A person employed in an office or bank to keep records, filings, and other administrative tasks",
  "clever": "Quick to understand, learn, and devise ideas",
  "click": "A short, sharp sound as of a switch being operated or of two hard objects coming quickly into contact",
  "client": "A person or organization using the services of a lawyer or other professional person or company",
  "climate": "The weather conditions prevailing in an area in general or over a long period",
  "climb": "Go or come up (a slope, incline, or staircase), especially by using the feet and sometimes the hands",
  "clock": "A mechanical or electrical device for measuring and indicating time, typically by means of hands on a dial or displayed digits",
  "close": "Only a short distance away or apart in space or time",
  "closely": "With little or no space or time in between",
  "cloth": "Woven or felted fabric made from wool, cotton, or a similar fiber",
  "clothes": "Items worn to cover the body",
  "cloud": "A visible mass of condensed water vapor floating in the atmosphere, typically high above the ground",
  "club": "An association or organization dedicated to a particular interest or activity",
  "clue": "A piece of evidence or information used in the detection of a crime or solving of a mystery",
  "coach": "An athletic instructor or trainer",
  "coal": "A combustible black or dark brown rock consisting mainly of carbonized plant matter, found mainly in underground deposits and widely used as fuel",
  "coast": "The part of the land adjoining or near the ocean",
  "coat": "An outer garment with sleeves, worn outdoors and typically extending below the hips",
  "code": "A system of words, letters, figures, or other symbols substituted for other words, letters, etc., especially for the purposes of secrecy",
  "coffee": "A hot drink made from the roasted and ground seeds (coffee beans) of a tropical shrub",
  "coin": "A flat, typically round piece of metal with an official stamp, used as money",
  "cold": "Of or at a low or relatively low temperature, especially when compared with the human body",
  "collapse": "Fall down or in; give way",
  "collect": "Bring or gather together (things, typically when scattered or widespread)",
  "collection": "The action or process of collecting someone or something",
  "college": "An educational institution or establishment, in particular one providing higher education or specialized training",
  "color": "The property possessed by an object of producing different sensations on the eye as a result of the way the object reflects or emits light",
  "column": "An upright pillar, typically cylindrical and made of stone or concrete, supporting an entablature, arch, or other structure or standing alone as a monument",
  "combination": "A joining or merging of different parts or qualities in which the component elements are individually distinct",
  "combine": "Join or merge to form a single unit or substance",
  "come": "Move or travel toward or into a place thought of as near or familiar to the speaker",
  "comfort": "A state of physical ease and freedom from pain or constraint",
  "comfortable": "Providing physical ease and relaxation",
  "command": "Give an authoritative order",
  "comment": "A verbal or written remark expressing an opinion or reaction",
  "commercial": "Concerned with or engaged in commerce",
  "commission": "An instruction, command, or duty given to a person or group of people",
  "commit": "Carry out or perpetrate (a mistake, crime, or immoral act)",
  "committee": "A group of people appointed for a specific function, typically consisting of members of a larger group",
  "common": "Occurring, found, or done often; prevalent",
  "communicate": "Share or exchange information, news, or ideas",
  "communication": "The imparting or exchanging of information or news",
  "community": "A group of people living in the same place or having a particular characteristic in common",
  "company": "A commercial business",
  "compare": "Estimate, measure, or note the similarity or dissimilarity between",
  "comparison": "A consideration or estimate of the similarities or dissimilarities between two or more people or things",
  "compete": "Strive to gain or win something by defeating or establishing superiority over others who are trying to do the same",
  "competition": "The activity or condition of competing",
  "complain": "Express dissatisfaction or annoyance about a state of affairs or an event",
  "complete": "Having all the necessary or appropriate parts",
  "completely": "Totally; utterly",
  "complex": "Consisting of many different and connected parts",
  "component": "A part or element of a larger whole, especially a part of a machine or vehicle",
  "compose": "Write or create (a work of art, especially music or poetry)",
  "composition": "The nature of something's ingredients or constituents; the way in which a whole or mixture is made up",
  "comprehensive": "Complete; including all or nearly all elements or aspects of something",
  "computer": "An electronic device for storing and processing data, typically in binary form, according to instructions given to it in a variable program",
  "concentrate": "Focus one's attention or mental effort on a particular object or activity",
  "concentration": "The action or power of focusing one's attention or mental effort",
  "concept": "An abstract idea; a general notion",
  "concern": "Relate to; be about",
  "concerned": "Worried, troubled, or anxious",
  "conclude": "Bring (something) to an end",
  "conclusion": "The end or finish of an event or process",
  "condition": "The state of something with regard to its appearance, quality, or working order",
  "conduct": "The manner in which a person behaves, especially on a particular occasion or in a particular context",
  "conference": "A formal meeting for discussion",
  "confidence": "The feeling or belief that one can rely on someone or something; firm trust",
  "confident": "Feeling or showing confidence in oneself; self-assured",
  "confirm": "Establish the truth or correctness of (something previously believed, suspected, or feared to be the case)",
  "conflict": "A serious disagreement or argument, typically a protracted one",
  "confuse": "Cause (someone) to become bewildered or perplexed",
  "confusion": "Lack of understanding; uncertainty",
  "connect": "Bring together or into contact so that a real or notional link is established",
  "connection": "A relationship in which a person, thing, or idea is linked or associated with something else",
  "conscious": "Aware of and responding to one's surroundings; awake",
  "consequence": "A result or effect of an action or condition",
  "conservative": "Holding to traditional attitudes and values and cautious about change or innovation, typically in relation to politics or religion",
  "consider": "Think carefully about (something), typically before making a decision",
  "considerable": "Notably large in size, amount, or extent",
  "consideration": "Careful thought, typically over a period of time",
  "consist": "Be composed or made up of",
  "consistent": "Acting or done in the same way over time, especially so as to be fair or accurate",
  "constant": "Occurring continuously over a period of time",
  "constantly": "Continuously over a period of time; always",
  "constitute": "Be (a part) of a whole",
  "construct": "Build or erect (something, typically a large structure)",
  "construction": "The building of something, typically a large structure",
  "consult": "Seek information or advice from (someone with expertise in a particular area)",
  "consumer": "A person who purchases goods and services for personal use",
  "contact": "The state or condition of physical touching",
  "contain": "Have or hold (someone or something) within",
  "container": "An object that can be used to hold or transport something",
  "contemporary": "Living or occurring at the same time",
  "content": "In a state of peaceful happiness",
  "contest": "An event in which people compete for supremacy in a particular activity or area",
  "context": "The circumstances that form the setting for an event, statement, or idea, and in terms of which it can be fully understood and assessed",
  "continue": "Persist in an activity or process",
  "continuous": "Forming an unbroken whole; without interruption",
  "contract": "A written or spoken agreement, especially one concerning employment, sales, or tenancy, that is intended to be enforceable by law",
  "contrast": "The state of being strikingly different from something else in juxtaposition or close association",
  "contribute": "Give (something, especially money) in order to help achieve or provide something",
  "contribution": "A gift or payment to a common fund or collection",
  "control": "The power to influence or direct people's behavior or the course of events",
  "convenient": "Fitting in well with a person's needs, activities, and plans",
  "convention": "A way in which something is usually done, especially within a particular area or activity",
  "conventional": "Based on or in accordance with what is generally done or believed",
  "conversation": "A talk, especially an informal one, between two or more people, in which news and ideas are exchanged",
  "convert": "Cause to change in form, character, or function",
  "convince": "Cause (someone) to believe firmly in the truth of something",
  "cook": "Prepare (food, a dish, or a meal) by combining and heating the ingredients in various ways",
  "cool": "Of or at a fairly low temperature",
  "copy": "A thing made to be similar or identical to another",
  "core": "The tough central part of various fruits, containing the seeds",
  "corner": "A place or angle where two or more sides or edges meet",
  "correct": "Free from error; in accordance with fact or truth",
  "cost": "The amount that has to be paid or spent to buy or obtain something",
  "cottage": "A small simple house, typically one near the lake or beach",
  "cotton": "A soft white fibrous substance that surrounds the seeds of a tropical and subtropical plant and is used as textile fiber and thread for sewing",
  "could": "Used to indicate possibility",
  "council": "An advisory, deliberative, or legislative body of people formally constituted and meeting regularly",
  "count": "Determine the total number of (a collection of items)",
  "counter": "A long flat-topped fixture in a store or bank across which business is conducted with customers",
  "country": "A nation with its own government, occupying a particular territory",
  "countryside": "The land and scenery of a rural area",
  "county": "A territorial division of some countries, forming the chief unit of local administration",
  "couple": "Two people or things of the same sort considered together",
  "courage": "The ability to do something that frightens one",
  "course": "An area of land or water on which a race takes place",
  "court": "A tribunal presided over by a judge, judges, or a magistrate in civil and criminal cases",
  "cousin": "A child of one's uncle or aunt",
  "cover": "Put something over or on top of (something else), typically in order to protect or conceal it",
  "cow": "A fully grown female animal of a domesticated breed of ox, kept to produce milk or beef",
  "crack": "A line on the surface of something along which it has split without breaking into separate parts",
  "craft": "An activity involving skill in making things by hand",
  "crash": "A sudden loud noise as of something breaking or hitting another object",
  "crazy": "Mentally deranged, especially as manifested in wild or aggressive behavior",
  "create": "Bring (something) into existence",
  "creation": "The action or process of bringing something into existence",
  "creative": "Relating to or involving the imagination or original ideas, especially in the production of an artistic work",
  "creature": "An animal, as distinct from a human being",
  "credit": "The ability of a customer to obtain goods or services before payment, based on the trust that payment will be made in the future",
  "crew": "A group of people who work on and operate a ship, aircraft, etc.",
  "crime": "An action or omission that constitutes an offense that may be prosecuted by the state and is punishable by law",
  "criminal": "A person who has committed a crime",
  "crisis": "A time of intense difficulty, trouble, or danger",
  "criterion": "A principle or standard by which something may be judged or decided",
  "critic": "A person who expresses an unfavorable opinion of something",
  "critical": "Expressing adverse or disapproving comments or judgments",
  "criticism": "The expression of disapproval of someone or something based on perceived faults or mistakes",
  "criticize": "Indicate the faults of (someone or something) in a disapproving way",
  "crop": "A cultivated plant that is grown as food, especially a grain, fruit, or vegetable",
  "cross": "A mark, object, or figure formed by two short intersecting lines or pieces",
  "crowd": "A large number of people gathered together, typically in a disorganized or unruly way",
  "crown": "A circular ornamental headdress worn by a monarch as a symbol of authority, usually made of or decorated with precious metals and gems",
  "crucial": "Decisive or critical, especially in the success or failure of something",
  "cruel": "Willfully causing pain or suffering to others, or feeling no concern about it",
  "cry": "Shed tears, typically as an expression of distress or pain",
  "cultural": "Relating to the ideas, customs, and social behavior of a society",
  "culture": "The arts and other manifestations of human intellectual achievement regarded collectively",
  "cup": "A small, bowl-shaped container for drinking from, typically having a handle",
  "cupboard": "A cabinet or small room with shelves for storing food, dishes, or utensils",
  "curiosity": "A strong desire to know or learn something",
  "curious": "Eager to know or learn something",
  "curl": "Form or cause to form into a curved or spiral shape",
  "currency": "A system of money in general use in a particular country",
  "current": "Belonging to the present time; happening or being used or done now",
  "currently": "At the present time",
  "curtain": "A piece of material suspended of a window to shut out the light or screen the room",
  "curve": "A line or outline which gradually deviates from being straight for some or all of its length",
  "custom": "A traditional and widely accepted way of behaving or doing something that is specific to a particular society, place, or time",
  "customer": "A person or organization that buys goods or services from a store or business",
  "cut": "Make an opening, incision, or wound in (something) with a sharp-edged tool or object",
  "cycle": "A series of events that are regularly repeated in the same order",
  "dad": "One's father",
  "daily": "Done, produced, or occurring every day or every weekday",
  "damage": "Physical harm caused to something in such a way as to impair its value, usefulness, or normal function",
  "dance": "Move rhythmically to music, typically following a set sequence of steps",
  "danger": "The possibility of suffering harm or injury",
  "dangerous": "Able or likely to cause harm or injury",
  "dare": "Have the courage to do something",
  "dark": "With little or no light",
  "darkness": "The partial or total absence of light",
  "data": "Facts and statistics collected together for reference or analysis",
  "date": "The day of the month or year as specified by a number",
  "daughter": "A girl or woman in relation to her parents",
  "day": "A period of twenty-four hours as a unit of time",
  "dead": "No longer alive",
  "deaf": "Lacking the power of hearing or having impaired hearing",
  "deal": "Take part in commercial trading of a particular commodity",
  "dear": "Regarded with deep affection",
  "death": "The action or fact of dying or being killed; the end of the life of a person or organism",
  "debate": "A formal discussion on a particular topic in a public meeting or legislative assembly, in which opposing arguments are put forward",
  "debt": "Something, typically money, that is owed or due",
  "decade": "A period of ten years",
  "decide": "Come to a resolution or settlement as a result of consideration",
  "decision": "A conclusion or resolution reached after consideration",
  "declare": "Say something in a solemn and emphatic manner",
  "decline": "Typically of something regarded as good become smaller, fewer, or less; decrease",
  "decorate": "Make (something) look more attractive by adding extra items or images to it",
  "decrease": "Make or become smaller or fewer in size, amount, intensity, or degree",
  "deep": "Extending far down from the top or surface",
  "deeply": "Very much; to a great degree",
  "defeat": "Win a victory over (someone) in a battle or other contest; overcome or beat",
  "defence": "The action of defending from or resisting attack",
  "defend": "Resist an attack made on (someone or something); protect from harm or danger",
  "define": "State or describe exactly the nature, scope, or meaning of",
  "definite": "Clearly stated or decided; not vague or doubtful",
  "definitely": "Without question and beyond doubt",
  "definition": "A statement of the exact meaning of a word, especially in a dictionary",
  "degree": "The amount, level, or extent to which something happens or is present",
  "delay": "Make (someone or something) late or slow",
  "deliberate": "Done consciously and intentionally",
  "delicate": "Very fine in texture or structure; of intricate workmanship or quality",
  "delight": "Great pleasure",
  "deliver": "Bring and hand over (a letter, parcel, or ordered goods) to the proper recipient or address",
  "delivery": "The action of delivering letters, packages, or ordered goods",
  "demand": "An insistent and peremptory request, made as if by right",
  "democracy": "A system of government by the whole population or all the eligible members of a state, typically through elected representatives",
  "demonstrate": "Clearly show the existence or truth of (something) by giving proof or evidence",
  "dentist": "A person qualified to treat the diseases and conditions that affect the teeth and gums",
  "deny": "State that one refuses to admit the truth or existence of",
  "department": "A division of a large organization such as a government, university, business, or shop, dealing with a specific subject or area of activity",
  "departure": "The action of leaving, especially to start a journey",
  "depend": "Be controlled or determined by",
  "dependent": "Requiring someone or something for financial, emotional, or other support",
  "deposit": "A sum of money placed or kept in a bank account, usually to gain interest",
  "depress": "Make (someone) feel utterly dispirited or dejected",
  "depth": "The distance from the top or surface to the bottom of something",
  "derive": "Obtain something from (a specified source)",
  "describe": "Give an account in words of (someone or something), including all the relevant characteristics, qualities, or events",
  "description": "A spoken or written representation or account of a person, object, or event",
  "desert": "A barren area of landscape where little precipitation occurs and, consequently, living conditions are hostile for plant and animal life",
  "deserve": "Do something or have or show qualities worthy of reward or punishment",
  "design": "A plan or drawing produced to show the look and function or workings of a building, garment, or other object before it is built or made",
  "designer": "A person who plans the look or workings of something prior to it being made, by preparing drawings or plans",
  "desire": "A strong feeling of wanting to have something or wishing for something to happen",
  "desk": "A piece of furniture with a flat or sloped surface and typically with drawers, at which one can read, write, or do other work",
  "desperate": "Feeling, showing, or involving a hopeless sense that a situation is so bad as to be impossible to deal with",
  "despite": "In spite of",
  "destroy": "Put an end to the existence of (something) by damaging or attacking it",
  "destruction": "The action or process of causing so much damage to something that it no longer exists or cannot be repaired",
  "detail": "An individual feature, fact, or item",
  "detailed": "Having many details or facts; very thorough",
  "detect": "Discover or identify the presence or existence of",
  "determination": "Firmness of purpose; resoluteness",
  "determine": "Cause (something) to occur in a particular way; be the decisive factor in",
  "develop": "Grow or cause to grow and become more mature, advanced, or elaborate",
  "development": "The process of developing or being developed",
  "device": "A thing made or adapted for a particular purpose, especially a piece of mechanical or electronic equipment",
  "devil": "The supreme spirit of evil",
  "diagram": "A simplified drawing showing the appearance, structure, or workings of something; a schematic representation",
  "diamond": "A precious stone consisting of a clear and colorless crystalline form of pure carbon, the hardest naturally occurring substance",
  "diary": "A book in which one keeps a daily record of events and experiences",
  "dictionary": "A book or electronic resource that lists the words of a language and gives their meaning",
  "die": "Stop living",
  "diet": "The kinds of food that a person, animal, or community habitually eats",
  "difference": "A point or way in which people or things are not the same",
  "different": "Not the same as another or each other; unlike in nature, form, or quality",
  "difficult": "Needing much effort or skill to accomplish, deal with, or understand",
  "difficulty": "The state or condition of being difficult",
  "dig": "Break up and move earth with a tool or machine, or with hands, paws, etc.",
  "digital": "Involving or relating to the use of computer technology",
  "dinner": "The main meal of the day, taken either around midday or in the evening",
  "direct": "Extending or moving in a straight line or by the shortest route",
  "direction": "A course along which someone or something moves",
  "directly": "Without changing direction or stopping",
  "director": "A person who is in charge of an activity, department, or organization",
  "dirt": "A substance, such as mud or dust, that soils someone or something",
  "dirty": "Covered or marked with an unclean substance",
  "disabled": "Having a physical or mental condition that limits movements, senses, or activities",
  "disagree": "Have or express a different opinion",
  "disappear": "Cease to be visible",
  "disappoint": "Fail to fulfill the hopes or expectations of (someone)",
  "disaster": "A sudden event, such as an accident or a natural catastrophe, that causes great damage or loss of life",
  "disc": "A flat, thin, circular object",
  "discipline": "The practice of training people to obey rules or a code of behavior, using punishment to correct disobedience",
  "discount": "A deduction from the usual cost of something",
  "discover": "Find (unexpectedly or during a search) something or someone",
  "discovery": "The action or process of discovering or being discovered",
  "discuss": "Talk about (something) with another person or group of people",
  "discussion": "The action or process of talking about something, typically in order to reach a decision or to exchange ideas",
  "disease": "A disorder of structure or function in a human, animal, or plant, especially one that produces specific signs or symptoms or that affects a specific location and is not simply a direct result of physical injury",
  "dish": "A shallow container for cooking or serving food",
  "disk": "A flat, thin, circular object",
  "dismiss": "Order or allow to leave; send away",
  "display": "Make a prominent exhibition of (something) in a place where it can be easily seen",
  "distance": "An amount of space between two things or people",
  "distant": "Far away in space or time",
  "distinct": "Recognizably different in nature from something else of a similar type",
  "distinguish": "Recognize or treat (someone or something) as different",
  "distribute": "Give shares of (something); apportion",
  "distribution": "The action of sharing something out among a number of recipients",
  "district": "An area of a country or city, especially one regarded as a distinct unit because of a particular characteristic",
  "disturb": "Interfere with the normal arrangement or functioning of",
  "divide": "Separate or be separated into parts",
  "division": "The action of separating something into parts or the process of being separated",
  "do": "Perform; carry out",
  "doctor": "A qualified practitioner of medicine; a physician",
  "document": "A piece of written, printed, or electronic matter that provides information or evidence or that serves as an official record",
  "dog": "A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, and a barking, howling, or whining voice",
  "doll": "A small model of a human figure, typically one used as a child's toy",
  "domain": "An area of territory owned or controlled by a ruler or government",
  "domestic": "Relating to the running of a home or to family relations",
  "dominant": "Most important, powerful, or influential",
  "door": "A hinged, sliding, or revolving barrier at the entrance to a building, room, or vehicle, or in the framework of a cupboard",
  "dot": "A small round mark or spot",
  "double": "Consisting of two equal, identical, or similar parts or things",
  "doubt": "A feeling of uncertainty or lack of conviction",
  "down": "Toward or in a lower place or position",
  "download": "Copy (data) from one computer system to another, typically over the internet",
  "downwards": "Toward a lower place or level",
  "dozen": "A group or set of twelve",
  "draft": "A preliminary version of a piece of writing",
  "drag": "Pull (someone or something) along forcefully, roughly, or with difficulty",
  "drama": "A play for theater, radio, or television",
  "draw": "Produce (a picture or diagram) by making lines and marks, especially with a pen or pencil, on paper",
  "drawer": "A boxlike storage compartment without a lid, made to slide horizontally in and out of a desk, chest, or other piece of furniture",
  "drawing": "A picture or diagram made with a pencil, pen, or crayon rather than paint, especially one drawn in monochrome",
  "dream": "A series of thoughts, images, and sensations occurring in a person's mind during sleep",
  "dress": "A one-piece garment for a woman or girl that covers the body and extends down over the legs",
  "drink": "Take a liquid into the mouth and swallow and absorb it",
  "drive": "Operate and control the direction and speed of a motor vehicle",
  "driver": "A person who drives a vehicle",
  "drop": "Let or make (something) fall vertically",
  "drug": "A medicine or other substance which has a physiological effect when ingested or otherwise introduced into the body",
  "drum": "A percussion instrument sounded by being struck with sticks or the hands, typically cylindrical, barrel-shaped, or bowl-shaped with a taut membrane over one or both ends",
  "drunk": "Affected by alcohol to the extent of losing control of one's faculties or behavior",
  "dry": "Free from moisture or liquid; not wet or moist",
  "duck": "A waterbird with a broad blunt bill, short legs, webbed feet, and a waddling gait",
  "due": "Expected to or planned to happen or arrive at a particular time",
  "dull": "Lacking interest or excitement",
  "dump": "A site for depositing trash",
  "during": "Throughout the course or duration of (a period of time)",
  "dust": "Fine, dry powder consisting of tiny particles of earth or waste matter lying on the ground or on surfaces or carried in the air",
  "duty": "A moral or legal obligation; a responsibility",
  "each": "Used to refer to every one of two or more people or things, regarded and identified separately",
  "ear": "The organ of hearing and equilibrium in vertebrates",
  "early": "Happening or done before the usual or expected time",
  "earn": "Obtain (money) in return for labor or services",
  "earth": "The planet on which we live; the world",
  "ease": "Absence of difficulty or effort",
  "easily": "Without difficulty or effort",
  "east": "The direction toward the point of the horizon where the sun rises at the equinoxes",
  "eastern": "Situated in, directed toward, or facing the east",
  "easy": "Achieved without great effort; presenting few difficulties",
  "eat": "Put (food) into the mouth and chew and swallow it",
  "economic": "Relating to economics or the economy",
  "economy": "The wealth and resources of a country or region, especially in terms of the production and consumption of goods and services",
  "edge": "The outside limit of an object, area, or surface",
  "edition": "A particular form or version of a published text",
  "editor": "A person who is in charge of and determines the final content of a text, particularly a newspaper or magazine",
  "educate": "Give intellectual, moral, and social instruction to (someone, especially a child), typically at a school or university",
  "education": "The process of receiving or giving systematic instruction, especially at a school or university",
  "effect": "A change which is a result or consequence of an action or other cause",
  "effective": "Successful in producing a desired or intended result",
  "effectively": "In such a manner as to achieve a desired result",
  "efficiency": "The state or quality of being efficient",
  "efficient": "Achieving maximum productivity with minimum wasted effort or expense",
  "effort": "A vigorous or determined attempt",
  "egg": "An oval or round object laid by a female bird, reptile, fish, or invertebrate, usually containing a developing embryo",
  "eight": "Equivalent to the product of two and four; one more than seven, or two less than ten; 8",
  "either": "Used before the first of two (or occasionally more) alternatives that are being specified",
  "elaborate": "Involving many carefully arranged parts or details; detailed and complicated in design and planning",
  "elbow": "The joint between the forearm and the upper arm",
  "elderly": "Of a person old or aging",
  "elect": "Choose (someone) to hold public office or some other position by voting",
  "election": "A formal and organized process of electing or being elected, especially of members of a political body",
  "electric": "Of, worked by, or charged with electricity",
  "electrical": "Concerned with, operating by, or producing electricity",
  "electricity": "A form of energy resulting from the existence of charged particles (such as electrons or protons), either statically as an accumulation of charge or dynamically as a current",
  "electronic": "Of a device having or operating with the aid of many small components, especially microchips and transistors, that control and direct an electric current",
  "element": "A part or aspect of something abstract, especially one that is essential or characteristic",
  "elementary": "Relating to the most rudimentary aspects of a subject",
  "elevator": "A platform or compartment housed in a shaft for raising and lowering people or things to different floors or levels",
  "eleven": "Equivalent to the sum of ten and one; one more than ten, or one less than twelve; 11",
  "else": "In addition; besides",
  "elsewhere": "In, at, or to some other place or other places",
  "email": "Messages distributed by electronic means from one computer user to one or more recipients via a network",
  "embarrassed": "Feeling or showing embarrassment",
  "emerge": "Move out of or away from something and come into view",
  "emergency": "A serious, unexpected, and often dangerous situation requiring immediate action",
  "emotion": "A strong feeling deriving from one's circumstances, mood, or relationships with others",
  "emotional": "Relating to a person's emotions",
  "emphasis": "Special importance, value, or prominence given to something",
  "emphasize": "Give special importance or prominence to (something) in speaking or writing",
  "empire": "An extensive group of states or countries under a single supreme authority, formerly especially an emperor or empress",
  "employ": "Give work to (someone) and pay them for it",
  "employee": "A person employed for wages or salary, especially at non-executive level",
  "employer": "A person or organization that employs people",
  "employment": "The state of having paid work",
  "empty": "Containing nothing; not filled or occupied",
  "enable": "Give (someone or something) the authority or means to do something",
  "encounter": "Unexpectedly experience or be faced with (something difficult or hostile)",
  "encourage": "Give support, confidence, or hope to (someone)",
  "end": "A final part of something, especially a period of time, an activity, or a story",
  "enemy": "A person who is actively opposed or hostile to someone or something",
  "energy": "The strength and vitality required for sustained physical or mental activity",
  "engage": "Occupy, attract, or involve (someone's interest or attention)",
  "engine": "A machine with moving parts that converts power into motion",
  "engineer": "A person who designs, builds, or maintains engines, machines, or public works",
  "engineering": "The branch of science and technology concerned with the design, building, and use of engines, machines, and structures",
  "enjoy": "Take delight or pleasure in (an activity or occasion)",
  "enormous": "Very large in size, quantity, or extent",
  "enough": "As much or as many as required",
  "ensure": "Make certain that (something) shall occur or be the case",
  "enter": "Come or go into (a place)",
  "enterprise": "A project or undertaking, typically one that is difficult or requires effort",
  "entertainment": "The action of providing or being provided with amusement or enjoyment",
  "enthusiasm": "Intense and eager enjoyment, interest, or approval",
  "enthusiastic": "Having or showing intense and eager enjoyment, interest, or approval",
  "entire": "With no part left out; whole",
  "entirely": "Completely (often used for emphasis)",
  "entrance": "An opening, such as a door, passage, or gate, that allows access to a place",
  "entry": "An act of going or coming into a place",
  "environment": "The surroundings or conditions in which a person, animal, or plant lives or operates",
  "environmental": "Relating to the natural world and the impact of human activity on its condition",
  "equal": "Being the same in quantity, size, degree, or value",
  "equally": "In the same manner or to the same extent",
  "equipment": "The necessary items for a particular purpose",
  "equivalent": "Equal in value, amount, function, meaning, etc.",
  "era": "A long and distinct period of history with a particular feature or characteristic",
  "error": "A mistake",
  "escape": "Break free from confinement or control",
  "especially": "To a great extent; very much",
  "essay": "A short piece of writing on a particular subject",
  "essential": "Absolutely necessary; extremely important",
  "essentially": "Used to emphasize the basic, fundamental, or intrinsic nature of a person, thing, or situation",
  "establish": "Set up (an organization, system, or set of rules) on a firm or permanent basis",
  "establishment": "The action of establishing something or being established",
  "estate": "An extensive area of land in the country, usually with a large house, owned by one person, family, or organization",
  "estimate": "Roughly calculate or judge the value, number, quantity, or extent of",
  "etc": "Used at the end of a list to indicate that further similar items are included",
  "ethical": "Relating to moral principles or the branch of knowledge dealing with these",
  "ethnic": "Relating to a population group with a common national or cultural tradition",
  "even": "Used to emphasize something surprising or extreme",
  "evening": "The period of time at the end of the day, usually from about 6 p.m. to bedtime",
  "event": "A thing that happens, especially one of importance",
  "eventually": "In the end, especially after a long delay, dispute, or series of problems",
  "ever": "At any time",
  "every": "Used before a singular noun to refer to all the individual members of a set without exception",
  "everybody": "Every person",
  "everyone": "Every person",
  "everything": "All things; all the things of a group or class",
  "everywhere": "In or to all places",
  "evidence": "The available body of facts or information indicating whether a belief or proposition is true or valid",
  "evil": "Profoundly immoral and malevolent",
  "exact": "Not approximated in any way; precise",
  "exactly": "Used to emphasize the accuracy of a figure or description",
  "exam": "A formal test of a person's knowledge or proficiency in a particular subject or skill",
  "examination": "A detailed inspection or investigation",
  "examine": "Inspect (someone or something) in detail to determine their nature or condition",
  "example": "A thing characteristic of its kind or illustrating a general rule",
  "excellent": "Extremely good; outstanding",
  "except": "Not including; other than",
  "exception": "A person or thing that is excluded from a general statement or does not follow a rule",
  "exchange": "An act of giving one thing and receiving another (especially of the same type or value) in return",
  "excitement": "A feeling of great enthusiasm and eagerness",
  "exciting": "Causing great enthusiasm and eagerness",
  "exclude": "Deny (someone) access to or bar (someone) from a place, group, or privilege",
  "excuse": "Seek to lessen the blame attaching to (a fault or offense); try to justify",
  "executive": "A person with senior managerial responsibility in a business organization",
  "exercise": "Activity requiring physical effort, carried out to sustain or improve health and fitness",
  "exhibit": "Publicly display (a work of art or item of interest) in an art gallery or museum or at a trade fair",
  "exhibition": "A public display of works of art or items of interest, held in an art gallery or museum or at a trade fair",
  "exist": "Have objective reality or being",
  "existence": "The fact or state of living or having objective reality",
  "exit": "A way out, especially of a public building, room, or vehicle",
  "expand": "Become or make larger or more extensive",
  "expansion": "The action of becoming larger or more extensive",
  "expect": "Regard (something) as likely to happen",
  "expectation": "A strong belief that something will happen or be the case in the future",
  "expense": "The cost required for something; the money spent on something",
  "expensive": "Costing a lot of money",
  "experience": "Practical contact with and observation of facts or events",
  "experiment": "A scientific procedure undertaken to make a discovery, test a hypothesis, or demonstrate a known fact",
  "expert": "A person who has a comprehensive and authoritative knowledge of or skill in a particular area",
  "explain": "Make (an idea, situation, or problem) clear to someone by describing it in more detail or revealing relevant facts or ideas",
  "explanation": "A statement or account that makes something clear",
  "explode": "Burst or shatter violently and noisily as a result of rapid combustion, excessive internal pressure, or other process",
  "explore": "Travel in or through (an unfamiliar country or area) in order to learn about or familiarize oneself with it",
  "explosion": "A violent and destructive shattering or blowing apart of something, as is caused by a bomb",
  "export": "Send (goods or services) to another country for sale",
  "expose": "Make (something) visible by uncovering it",
  "exposure": "The state of being exposed to contact with something",
  "express": "Convey (a thought or feeling) in words or by gestures and conduct",
  "expression": "The process of making known one's thoughts or feelings",
  "extend": "Cause to cover a larger area; make longer or wider",
  "extension": "A part that is added to something to enlarge or prolong it",
  "extensive": "Covering or affecting a large area",
  "extent": "The area covered by something",
  "external": "Belonging to or forming the outer surface or structure of something",
  "extra": "Added to an existing or usual amount or number; additional",
  "extraordinary": "Very unusual or remarkable",
  "extreme": "Reaching a high or the highest degree; very great",
  "extremely": "To a very great degree; very",
  "eye": "Each of a pair of globular organs in the head through which people and vertebrate animals see",
};
